---
# tasks file for python
# - name: Install python3
#   ansible.builtin.apt:
#     name: python3
#     state: present
#     update_cache: true
#   become: true
- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true
  become: true
- name: Install docker python package
  ansible.builtin.pip:
    name: docker>=5.0.0
